### ISSUE TITLE
In Admin "vs" User-Seminar side-by-side view, add "Copy to clipboard" functionality

### ISSUE THREAD

**Issue by fwolfst** [ecovillage/neseri#12]
In the view where an admin sees the admin- and the user copy of a seminar side-by-side, the admin probably wants to copy the values of the admin seminar into some other applications.
For this, a small button to copy the value of a relevant field into the systems clipboard would be handy.

Work can happen in the master-branch which is probably somewhat dirty - I will try to clean the state up next week.

**Comment by TheRealSyler** [comment]
https://github.com/TheRealSyler/neseri/commit/2b2f11438d51457a6ff4c047b4697d8c98801c18
this commit adds a script that loops through each element with the `copy` class and replaces that element with a div containing the element and a button that copies the value of the element, only works for elements that have the value property, it should be fine for our use case.

https://github.com/TheRealSyler/neseri/commit/221b805baef53eb29c7d5fd65ea8c8d935415203
this commit adds the `copy` class to the fields in `admin/admin_seminars`, not sure if this is the best way to do it.

**Comment by fwolfst** [comment]
I didnt test but trust you, just fire a PR or commit to origin/master.

**Comment by fwolfst** [comment]
cherry-picked
